#!/usr/bin/env node

const os = require('os');
const fs = require('fs');
const path = require('path');
// const prompts = require('prompts');

const configPath = path.join(os.homedir(), '.{{projectName}}rc');

(async () => {
  console.log('creating project config file...');

  let config = {};
  if (fs.existsSync(configPath)) {
    try {
      const parsedConfig = JSON.parse(fs.readFileSync(configPath, 'utf8'));
      if (typeof parsedConfig === 'object') {
        config = parsedConfig;
      }
    } catch (err) { /* swallow ParserErrors */ }
  }

  /***
   * add code here that should be added
   * to this cli's config file...
   ***/

  if (Object.keys(config).length === 0) {
    config.temp = 'this is just for reference...you should replace this.';
  }

  try {
    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));

    console.log(`[+] ${configPath} created successfully`);

    process.exit(0);
  } catch (err) {
    console.error(`postinstall error\n\n${err.message}`);
    process.exit(1);
  }
})();
